### ISSUE TITLE
Blobs persistance needs support for DefaultAzureCredential()

### ISSUE THREAD

**Issue by sainzg** [petabridge/Akka.Persistence.Azure#140]
Connection string isn't enough when it comes to Azure Blob Storage as for security it needs to be able to run using DefaultAzureCredential() in order to delegate access to managed identity

Maybe just adding an extra param in app.conf in the connection section as boolean which in turns this will indicate to the constructor to pass DefaultAzureCredential() as the second parameter for the connection function

**Comment by Aaronontheweb** [comment]
@sainzg agree - we use managed identities for our own K8s pods and we should be able to use this...

**Comment by sainzg** [comment]
@Aaronontheweb thank you, this is something really needed to secure azure blobs, so please let me know when it becomes available as I am able to test it pretty quick on my end.

**Comment by Arkatufus** [comment]
In order to implement this, we'd need to upgrade the SDK to the latest Azure.Storage.Blobs nuget package, this will change the code quite a bit, namely switching to .NET 8.0 language version for IAsyncEnumerator support and changes to the blob API itself.

**Comment by Arkatufus** [comment]
SDK upgrade PR: #151

**Comment by Arkatufus** [comment]
Some people are under the impression that the new `DefaultAzureCredential()` are made exclusively to work with the new wave of azure clients (the new SDKs with the `Azure.*` pattern`. I can try to see if this can work with the old clients, but would not be able to test them under development mode. I'd need a real Azure account to test this with.

**Comment by Arkatufus** [comment]
For Azure Tables, should we wait for [`Azure.Data.Tables`](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/tables/Azure.Data.Tables) to reach GA, or should we implement this now? We can use a feature branch and do a preview release for the beta release.

**Comment by Aaronontheweb** [comment]
> Some people are under the impression that the new `Azure.Identity` `DefaultAzureCredential()` are made exclusively to work with the new wave of azure clients (the new SDKs with the `Azure.*` pattern`. I can try to see if this can work with the old clients, but would not be able to test them under development mode. I'd need a real Azure account to test this with.

I don't think we necessarily need a test environment for this, since that's an internal implementation detail of the Sdk. We just need a setting that allow users to resolve the default azure credential for authenticating against these resources. It's their fault if they didn't set their environment up to allow this correctly.

As for the Sdk issues - there's a newer SDK for Cosmos: https://www.nuget.org/packages/Microsoft.Azure.CosmosDB.Table/ - will that allow you to use the default credentials?

**Comment by Arkatufus** [comment]
Well, I still need to check that my code is actually doing what its supposed to.

`Microsoft.Azure.CosmoDB.Table` is the one I use in the PR, the newest client is the `Azure.Data.Tables` package, and its still in beta.

**Comment by Aaronontheweb** [comment]
> Microsoft.Azure.CosmoDB.Table is the one I use in the PR,

Confusingly enough, no it's not - we use `Microsoft.Azure.Cosmos.Table`

https://github.com/petabridge/Akka.Persistence.Azure/blob/9c79c55ea5fb0469aa4ad41c18b1a635c7f40081/src/Akka.Persistence.Azure/Akka.Persistence.Azure.csproj#L19

Which is older than `Microsoft.Azure.CosmoDB.Table` 

This issue inspired this tweet: https://twitter.com/Aaronontheweb/status/1382093167982428160

**Comment by Arkatufus** [comment]
Ah, ok, I guess they really have way too many packages for CosmoDB. I'll give it a look-see.

**Comment by Arkatufus** [comment]
From the Nuget package description:

> NOTE: This .NET Framework library is in maintenance mode and it will be deprecated soon. Please upgrade to the new .NET Standard library ([Microsoft.Azure.Cosmos.Table](https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table)) to continue to get the latest features supported. 

We're using the latest in the last PR, which is [`Microsoft.Azure.Cosmos.Table`](https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table)

**Comment by Aaronontheweb** [comment]
If we can implement this feature using whatever we're using now, let's do that.

**Comment by Arkatufus** [comment]
`AzureDefaultIdentity` is not supported for Azure Tables, so I can not implement that. Implementing it for Blob Storage is quite straight forward though.

**Comment by sainzg** [comment]
Right, it is only needed for blobs
