### ISSUE TITLE
Allow private access on snapshot container

### ISSUE THREAD

**Issue by MattiasJakobsson** [petabridge/Akka.Persistence.Azure#144]
At the moment the access on the snapshot container is hard coded to public (https://github.com/petabridge/Akka.Persistence.Azure/blob/dev/src/Akka.Persistence.Azure/Snapshot/AzureBlobSnapshotStore.cs#L73). We would like to set the access to private in our case, so it would be nice to have a setting for this.

We're also creating the container and table from outside of our application, so it would be nice to have a setting to disable the container creation (something like this maybe: https://github.com/akkadotnet/akka.net/blob/dev/src/contrib/persistence/Akka.Persistence.Sqlite/sqlite.conf#L29).

I'd happily make the changes required and open a PR. I'd just like to get the maintainers thoughts first.

**Comment by davidhagg** [comment]
Any comments about this issue? We're doing a security review and this is an open issue for us. We're happy to do a PR.

**Comment by Aaronontheweb** [comment]
> At the moment the access on the snapshot container is hard coded to public (https://github.com/petabridge/Akka.Persistence.Azure/blob/dev/src/Akka.Persistence.Azure/Snapshot/AzureBlobSnapshotStore.cs#L73). We would like to set the access to private in our case, so it would be nice to have a setting for this.

Yes, we should absolutely do that.

**Comment by Arkatufus** [comment]
The PR #150 only addressed half of the issue. Still need a configuration to change container public access level.

**Comment by MattiasJakobsson** [comment]
You're right @Arkatufus, I just fixed our case in #150. I've opened a another pr (#152) to handle public access level as well.
