### ISSUE TITLE
Support secret rotation

### ISSUE THREAD

**Issue by pshrosbree** [petabridge/Akka.Persistence.Azure#20]
Support for secret rotation is required for production systems.
Usually, secrets for Azure storage are kept in Key Vault, but there is no need to take a hard dependency on Key Vault. Any source would do.
Instead of constructors taking a connection string, they could take a  `Func<Task<string>>` that will return the connection string. When an Azure storage API call is made that returns `401 Not Authorized`, this function is called to refresh the connection string. It might be a good idea to have a worker which the journal's supervisor policy recreates with a new connection string when it fails with a 401.
Alternatively, an `IActorRef` could be passed which would respond to appropriate messages for connection strings.
Or the settings object be the source of the update, but in a similar fashion to the above.

**Comment by Aaronontheweb** [comment]
I think this is probably addressed by `AzureDefaultCredential` support, which we just merged in via https://github.com/petabridge/Akka.Persistence.Azure/pull/237
