### ISSUE TITLE
Persistence Recovery Failure Loop

### ISSUE THREAD

**Issue by littleAndroidMan** [petabridge/Akka.Persistence.Azure#386]
Ran into a bug with persistence that is preventing an actor from being started successfully due to repeated persistence recovery failures, even after purging the persistence store (Azure Table/Blob Storage) via the API calls provided in the Persistent Actor.

To reproduce:
1. Induce a persistence recovery failure by changing the properties of a persisted journaled message and attempting to play back the bad message. (I did this via extending a persisted object with new properties - I did not change any pre-existing property names or values), but the deploy to our cluster with the new code timed out and resulted in a corruption of the persistence store for actors that replayed the changed object. 

This error appears over and over in the logs once the wire format is corrupted:

`(2024-04-22T16:58:34.5152956Z, 2024-04-22T17:32:34.1147660Z] akka_address: akka.tcp://Backplane@backplane-0.backplane:9223 cluster_role: rtf exceptiontype: Azure.Data.Tables.TableTransactionFailedException level: warning LongSum`

2. In the event handler for OnRecoveryFailure, invoke the commands to purge the persistence store of all data:
`DeleteMessages(long.MaxValue);
 DeleteSnapshots(new SnapshotSelectionCriteria(long.MaxValue));`

3. When the actor restarts, it still gets a persistence recovery failure, except this time it's looking for the 0th message:
`[ERROR][04/22/2024 19:59:17.542Z][Thread 0033][akka.tcp://Backplane@backplane-0.backplane:9223/system/sharding/users/2/sduser-7877102] Persistence failure when replaying events for persistenceId [sduser-7877102]. Last known sequence number [0]`

From that point on it's stuck in an endless loop of failing to recover, attempting to purge all its messages, and then failing on the 0th message, which shouldn't exist any more.

**Comment by Arkatufus** [comment]
What serializer do you use to serialize your journal message?

**Comment by littleAndroidMan** [comment]
Hyperion

**Comment by Arkatufus** [comment]
Seems like the bug was not in `Akka.Persistence.Azure` but actually stemmed from `Akka.Persistence` package in `Akka.Persistence.Eventsourced.cs`.

https://github.com/akkadotnet/akka.net/blob/a19b825f4a1838bac766af0f073e3debb4cf4546/src/core/Akka.Persistence/Eventsourced.cs#L460-L461

* If `toSequenceNr` is `long.MaxValue`, the value is clamped to `LastSequenceNr`. 
* Since the failure happened during recovery, `LastSequenceNr` has not been initialized and the default value is 0. 
* Since the `toSequenceNr` is clamped to 0, nothing will be deleted.

**Comment by Arkatufus** [comment]
OK, after looking more into this, this code was introduced here:
https://github.com/akkadotnet/akka.net/pull/4892

It was a direct port of this Akka code:
https://github.com/akka/akka/issues/25487

Which is required for some persistence plugins to function properly.

**Comment by Arkatufus** [comment]
@littleAndroidMan 

Reverting the cause of this issue would affect other persistence plugins in a dangerous way, the only solution for this is to manually delete the offending corrupted journal entries from Azure Table.

You can use [Microsoft Azure Storage Explorer](https://azure.microsoft.com/en-us/products/storage/storage-explorer/) to do this. 
* Connect to your Azure resource from within the application.
  * Right click on the "Storage Accounts" entry in the tree view on the left.
  * Click on "Connect to Azure Storage..." in the context menu.
* Expand the appropriate storage account name in the tree view on the left.
* Expand the "Tables" entry in the tree view on the left.
* Double-click the table to open it, this is the "AkkaPersistenceDefaultTable" table by default, check your code if you changed the table name.
* Create a new query by clicking the "Query" icon on the top left of the table view
* In the query window set:
  * PartitionKey = [the corrupted persistence id]
  * And RowKey <> highestSequenceNr
* Run the query.
* Select all rows.
* Right click on the selected rows and click "Delete" on the context menu.
* Make sure that you re-run the query again to make sure that all rows were deleted.

**Comment by littleAndroidMan** [comment]
@Arkatufus 

Thanks! I'll keep these instructions so I can purge corrupted entries in the future (hopefully I won't have to).
