### ISSUE TITLE
Needs documentation for use.

### ISSUE THREAD

**Issue by yozepi** [petabridge/Akka.Persistence.Azure#97]
I would love to try this out but I can't find any docs on the Hocon configuration.

**Comment by motmot80** [comment]
I struggled a bit, too. A link to the `reference.conf` in the main `README.MD` would really help. The configuration itself is pretty simple. You just need to put in your connection string and choose a blod-storage container and a table name.

**Comment by motmot80** [comment]
And you should not forget to activate the plugins by.

`akka.persistence.journal.plugin = akka.persistence.journal.azure-table`
`akka.persistence.snapshot-store.plugin = akka.persistence.snapshot-store.azure-blob-store`
